import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import './globals.css';
import NextAuthProvider from '@/providers/NextAuth';

import { ThemeProvider } from '@/components/theme-provider';
import Footer from '@/components/Footer';
import Header from '@/components/Header';

const notoSansJP = Noto_Sans_JP({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ja">
            <body className={notoSansJP.className}>
                <NextAuthProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <div className="w-screen h-full">
                            {/* ヘッダー */}
                            <div className="w-screen h-18 sticky top-0">
                                <Header />
                            </div>
                            {/* メイン */}
                            <div className="w-screen h-full">{children}</div>
                            {/* フッター */}
                            <div className="w-screen h-18 fixed bottom-0">
                                <Footer />
                            </div>
                        </div>
                    </ThemeProvider>
                </NextAuthProvider>
            </body>
        </html>
    );
}
