import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import './globals.css';
import NextAuthProvider from '@/providers/NextAuth';
import Header from '@/components/Header';
import { ThemeProvider } from '@/components/theme-provider';

const notoSansJP = Noto_Sans_JP({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ja">
            <body className={notoSansJP.className}>
                <div className="flex flex-col w-screen h-screen">
                    <NextAuthProvider>
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="system"
                            enableSystem
                            disableTransitionOnChange
                        >
                            <Header />
                            {children}
                        </ThemeProvider>
                    </NextAuthProvider>
                </div>
            </body>
        </html>
    );
}
